from celeri.celeri_util import (
    align_velocities,
    diagnose_matrix,
    get_2component_index,
    get_3component_index,
    get_keep_index_12,
    get_logger,
    get_newest_run_folder,
    get_segment_oblique_projection,
    get_transverse_projection,
    interleave2,
    interleave3,
    read_run,
    wrap2360,
)
from celeri.cli import parse_args, process_args
from celeri.config import Config, get_config
from celeri.mesh import Mesh, MeshConfig
from celeri.model import (
    Model,
    assign_block_labels,
    build_model,
    create_output_folder,
    merge_geodetic_data,
    process_sar,
    process_segment,
    process_station,
    read_data,
    station_row_keep,
)
from celeri.operators import (
    Operators,
    build_operators,
    get_block_strain_rate_to_velocities_partials,
    get_eigenvalues_and_eigenvectors,
    get_elastic_operator_single_mesh,
    get_full_dense_operator,
    get_full_dense_operator_eigen,
    get_global_float_block_rotation_partials,
    get_h_matrices_for_tde_meshes,
    get_mogi_to_velocities_partials,
    get_qp_all_inequality_operator_and_data_vector,
    get_qp_slip_rate_inequality_operator_and_data_vector,
    get_qp_tde_inequality_operator_and_data_vector,
    get_rotation_to_slip_rate_partials,
    get_rotation_to_tri_slip_rate_partials,
    get_rotation_to_velocities_partials,
    get_segment_station_operator_okada,
    get_slip_rate_bounds,
    get_slip_rate_constraints,
    get_tde_to_velocities_single_mesh,
    get_weighting_vector_single_mesh_for_col_norms,
)
from celeri.output import write_output, write_output_supplemental
from celeri.plot import (
    get_default_plotting_dict,
    plot_common_elements,
    plot_estimation_summary,
    plot_fault_geometry,
    plot_input_summary,
    plot_matrix_abs_log,
    plot_mesh_mode,
    plot_meshes,
    plot_residuals,
    plot_rotation_components,
    plot_segment_displacements,
    plot_segment_rates,
    plot_strain_rate_components_for_block,
    plot_tde_boundary_condition_labels,
    plot_vel_arrows_elements,
    plot_vels,
)
from celeri.solve import (
    assemble_and_solve_dense,
    build_and_solve_dense,
    build_and_solve_dense_no_meshes,
    lsqlin_qp,
)
from celeri.spatial import (
    get_okada_displacements,
    get_shared_sides,
    get_tde_to_velocities,
    get_tri_displacements,
)

try:
    from importlib.metadata import version

    __version__ = version("celeri")
except Exception:
    __version__ = "unknown"

__all__ = [
    "Config",
    "Mesh",
    "MeshConfig",
    "Model",
    "Operators",
    "__version__",
    "align_velocities",
    "assemble_and_solve_dense",
    "assign_block_labels",
    "build_and_solve_dense",
    "build_and_solve_dense_no_meshes",
    "build_model",
    "build_operators",
    "create_output_folder",
    "diagnose_matrix",
    "get_2component_index",
    "get_3component_index",
    "get_block_strain_rate_to_velocities_partials",
    "get_config",
    "get_default_plotting_class",
    "get_eigenvalues_and_eigenvectors",
    "get_elastic_operator_single_mesh",
    "get_full_dense_operator",
    "get_full_dense_operator_eigen",
    "get_global_float_block_rotation_partials",
    "get_h_matrices_for_tde_meshes",
    "get_keep_index_12",
    "get_logger",
    "get_mogi_to_velocities_partials",
    "get_newest_run_folder",
    "get_okada_displacements",
    "get_qp_all_inequality_operator_and_data_vector",
    "get_qp_slip_rate_inequality_operator_and_data_vector",
    "get_qp_tde_inequality_operator_and_data_vector",
    "get_rotation_to_slip_rate_partials",
    "get_rotation_to_tri_slip_rate_partials",
    "get_rotation_to_velocities_partials",
    "get_segment_oblique_projection",
    "get_segment_station_operator_okada",
    "get_shared_sides",
    "get_slip_rate_bounds",
    "get_slip_rate_constraints",
    "get_tde_to_velocities",
    "get_tde_to_velocities_single_mesh",
    "get_transverse_projection",
    "get_tri_displacements",
    "get_weighting_vector_single_mesh_for_col_norms",
    "interleave2",
    "interleave3",
    "lsqlin_qp",
    "merge_geodetic_data",
    "parse_args",
    "plot_common_elements",
    "plot_estimation_summary",
    "plot_fault_geometry",
    "plot_input_summary",
    "plot_matrix_abs_log",
    "plot_mesh_mode",
    "plot_meshes",
    "plot_residuals",
    "plot_rotation_components",
    "plot_segment_displacements",
    "plot_segment_rates",
    "plot_strain_rate_components_for_block",
    "plot_tde_boundary_condition_labels",
    "plot_vel_arrows_elements",
    "plot_vels",
    "process_args",
    "process_sar",
    "process_segment",
    "process_station",
    "read_data",
    "read_run",
    "station_row_keep",
    "wrap2360",
    "write_output",
    "write_output_supplemental",
]
